class Arguments(object):
    Host = 'Host'
    Port = 'Port'
    Username = 'Username'
    Password = 'Password'
    SearchMethod = 'SearchMethod'
    SearchArgument = 'SearchArgument'
    NetworkName = 'NetworkName'
    IsVDS = 'IsVDS'
    DatacenterName = 'DatacenterName'
    DatastoreName = 'DatastoreName'
    ResourcePool = 'ResourcePool'
    ClusterName = 'ClusterName'
    VMDK_Path = 'VMDK_Path'
    OVF_Path = 'OVF_Path'
    NewName = 'NewName'
    HardDiskSize = 'HardDiskSize'
    HardDiskType = 'HardDiskType'
