#!/usr/bin/ruby env

require "socket"

$hostname = Socket.gethostname

forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/apt', :latest
mod 'stahnma/epel', :latest
mod 'garethr/docker', :latest
mod 'stankevich/python', :latest
